
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/hashicorp/memberlist"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hexablock/blox"

[[constraint]]
  branch = "master"
  name = "github.com/hexablock/go-kelips"

[[constraint]]
  branch = "master"
  name = "github.com/hexablock/hexalog"

[[constraint]]
  branch = "master"
  name = "github.com/hexablock/hexatype"

[[constraint]]
  branch = "master"
  name = "github.com/hexablock/log"

[[constraint]]
  branch = "master"
  name = "github.com/hexablock/phi"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.8.2"
