// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package fidias is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	KeyState
	KeyValuePair
*/
package fidias

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyState struct {
	// Actual key
	Key []byte `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Location id or last entry or id
	Marker []byte `protobuf:"bytes,2,opt,name=Marker,proto3" json:"Marker,omitempty"`
	// Total known height of the key
	Height uint32 `protobuf:"varint,3,opt,name=Height" json:"Height,omitempty"`
}

func (m *KeyState) Reset()                    { *m = KeyState{} }
func (m *KeyState) String() string            { return proto.CompactTextString(m) }
func (*KeyState) ProtoMessage()               {}
func (*KeyState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeyState) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyState) GetMarker() []byte {
	if m != nil {
		return m.Marker
	}
	return nil
}

func (m *KeyState) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type KeyValuePair struct {
	Key []byte `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Arbitrary data
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	// Artibrary integer flags
	Flags int64 `protobuf:"varint,3,opt,name=Flags" json:"Flags,omitempty"`
	// Entry id resulting in the view
	Modification []byte `protobuf:"bytes,4,opt,name=Modification,proto3" json:"Modification,omitempty"`
	// Entry height
	Height uint32 `protobuf:"varint,5,opt,name=Height" json:"Height,omitempty"`
}

func (m *KeyValuePair) Reset()                    { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string            { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()               {}
func (*KeyValuePair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeyValuePair) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValuePair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValuePair) GetFlags() int64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *KeyValuePair) GetModification() []byte {
	if m != nil {
		return m.Modification
	}
	return nil
}

func (m *KeyValuePair) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*KeyState)(nil), "fidias.KeyState")
	proto.RegisterType((*KeyValuePair)(nil), "fidias.KeyValuePair")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FidiasRPC service

type FidiasRPCClient interface {
	// Get key-value pair from remote
	GetKeyRPC(ctx context.Context, in *KeyValuePair, opts ...grpc.CallOption) (*KeyValuePair, error)
	// Send key-location id pairs
	RelocateRPC(ctx context.Context, opts ...grpc.CallOption) (FidiasRPC_RelocateRPCClient, error)
	// Send block id and journal value
	RelocateBlocksRPC(ctx context.Context, opts ...grpc.CallOption) (FidiasRPC_RelocateBlocksRPCClient, error)
}

type fidiasRPCClient struct {
	cc *grpc.ClientConn
}

func NewFidiasRPCClient(cc *grpc.ClientConn) FidiasRPCClient {
	return &fidiasRPCClient{cc}
}

func (c *fidiasRPCClient) GetKeyRPC(ctx context.Context, in *KeyValuePair, opts ...grpc.CallOption) (*KeyValuePair, error) {
	out := new(KeyValuePair)
	err := grpc.Invoke(ctx, "/fidias.FidiasRPC/GetKeyRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fidiasRPCClient) RelocateRPC(ctx context.Context, opts ...grpc.CallOption) (FidiasRPC_RelocateRPCClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FidiasRPC_serviceDesc.Streams[0], c.cc, "/fidias.FidiasRPC/RelocateRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &fidiasRPCRelocateRPCClient{stream}
	return x, nil
}

type FidiasRPC_RelocateRPCClient interface {
	Send(*KeyState) error
	Recv() (*KeyState, error)
	grpc.ClientStream
}

type fidiasRPCRelocateRPCClient struct {
	grpc.ClientStream
}

func (x *fidiasRPCRelocateRPCClient) Send(m *KeyState) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fidiasRPCRelocateRPCClient) Recv() (*KeyState, error) {
	m := new(KeyState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fidiasRPCClient) RelocateBlocksRPC(ctx context.Context, opts ...grpc.CallOption) (FidiasRPC_RelocateBlocksRPCClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_FidiasRPC_serviceDesc.Streams[1], c.cc, "/fidias.FidiasRPC/RelocateBlocksRPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &fidiasRPCRelocateBlocksRPCClient{stream}
	return x, nil
}

type FidiasRPC_RelocateBlocksRPCClient interface {
	Send(*KeyState) error
	Recv() (*KeyState, error)
	grpc.ClientStream
}

type fidiasRPCRelocateBlocksRPCClient struct {
	grpc.ClientStream
}

func (x *fidiasRPCRelocateBlocksRPCClient) Send(m *KeyState) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fidiasRPCRelocateBlocksRPCClient) Recv() (*KeyState, error) {
	m := new(KeyState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for FidiasRPC service

type FidiasRPCServer interface {
	// Get key-value pair from remote
	GetKeyRPC(context.Context, *KeyValuePair) (*KeyValuePair, error)
	// Send key-location id pairs
	RelocateRPC(FidiasRPC_RelocateRPCServer) error
	// Send block id and journal value
	RelocateBlocksRPC(FidiasRPC_RelocateBlocksRPCServer) error
}

func RegisterFidiasRPCServer(s *grpc.Server, srv FidiasRPCServer) {
	s.RegisterService(&_FidiasRPC_serviceDesc, srv)
}

func _FidiasRPC_GetKeyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValuePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FidiasRPCServer).GetKeyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fidias.FidiasRPC/GetKeyRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FidiasRPCServer).GetKeyRPC(ctx, req.(*KeyValuePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _FidiasRPC_RelocateRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FidiasRPCServer).RelocateRPC(&fidiasRPCRelocateRPCServer{stream})
}

type FidiasRPC_RelocateRPCServer interface {
	Send(*KeyState) error
	Recv() (*KeyState, error)
	grpc.ServerStream
}

type fidiasRPCRelocateRPCServer struct {
	grpc.ServerStream
}

func (x *fidiasRPCRelocateRPCServer) Send(m *KeyState) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fidiasRPCRelocateRPCServer) Recv() (*KeyState, error) {
	m := new(KeyState)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FidiasRPC_RelocateBlocksRPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FidiasRPCServer).RelocateBlocksRPC(&fidiasRPCRelocateBlocksRPCServer{stream})
}

type FidiasRPC_RelocateBlocksRPCServer interface {
	Send(*KeyState) error
	Recv() (*KeyState, error)
	grpc.ServerStream
}

type fidiasRPCRelocateBlocksRPCServer struct {
	grpc.ServerStream
}

func (x *fidiasRPCRelocateBlocksRPCServer) Send(m *KeyState) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fidiasRPCRelocateBlocksRPCServer) Recv() (*KeyState, error) {
	m := new(KeyState)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FidiasRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fidias.FidiasRPC",
	HandlerType: (*FidiasRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKeyRPC",
			Handler:    _FidiasRPC_GetKeyRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RelocateRPC",
			Handler:       _FidiasRPC_RelocateRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RelocateBlocksRPC",
			Handler:       _FidiasRPC_RelocateBlocksRPC_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcb, 0x4c, 0xc9, 0x4c, 0x2c, 0x56, 0xf2, 0xe1,
	0xe2, 0xf0, 0x4e, 0xad, 0x0c, 0x2e, 0x49, 0x2c, 0x49, 0x15, 0x12, 0xe0, 0x62, 0xf6, 0x4e, 0xad,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0x31, 0x85, 0xc4, 0xb8, 0xd8, 0x7c, 0x13, 0x8b,
	0xb2, 0x53, 0x8b, 0x24, 0x98, 0xc0, 0x82, 0x50, 0x1e, 0x48, 0xdc, 0x23, 0x35, 0x33, 0x3d, 0xa3,
	0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0x37, 0x08, 0xca, 0x53, 0xea, 0x60, 0xe4, 0xe2, 0xf1, 0x4e,
	0xad, 0x0c, 0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0x48, 0xcc, 0x2c, 0xc2, 0x62, 0xa4, 0x08, 0x17, 0x2b,
	0x58, 0x1a, 0x6a, 0x22, 0x84, 0x03, 0x12, 0x75, 0xcb, 0x49, 0x4c, 0x2f, 0x06, 0x9b, 0xc7, 0x1c,
	0x04, 0xe1, 0x08, 0x29, 0x71, 0xf1, 0xf8, 0xe6, 0xa7, 0x64, 0xa6, 0x65, 0x26, 0x27, 0x96, 0x64,
	0xe6, 0xe7, 0x49, 0xb0, 0x80, 0xb5, 0xa0, 0x88, 0x21, 0x39, 0x85, 0x15, 0xd9, 0x29, 0x46, 0xfb,
	0x18, 0xb9, 0x38, 0xdd, 0xc0, 0x7e, 0x0c, 0x0a, 0x70, 0x16, 0xb2, 0xe4, 0xe2, 0x74, 0x4f, 0x2d,
	0xf1, 0x4e, 0xad, 0x04, 0x71, 0x44, 0xf4, 0x20, 0x9e, 0xd7, 0x43, 0x76, 0xaa, 0x14, 0x56, 0x51,
	0x25, 0x06, 0x21, 0x73, 0x2e, 0xee, 0xa0, 0xd4, 0x9c, 0xfc, 0xe4, 0xc4, 0x92, 0x54, 0x90, 0x66,
	0x01, 0x24, 0x65, 0xe0, 0x60, 0x93, 0xc2, 0x10, 0x51, 0x62, 0xd0, 0x60, 0x34, 0x60, 0x14, 0xb2,
	0xe5, 0x12, 0x84, 0x69, 0x74, 0xca, 0xc9, 0x4f, 0xce, 0x2e, 0x26, 0x49, 0x7b, 0x12, 0x1b, 0x38,
	0xa2, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xe0, 0x85, 0x8b, 0xb5, 0x01, 0x00, 0x00,
}
