
version: '2'
services:
  bootstrap:
    image: fid
    command: ["-debug"]
    ports:
      - "8800:8800"
      - "9090:9090"
      - "42100:42100/udp"
      - "42100:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "bootstrap:32100"
      FID_DATA_ADV_ADDR: "bootstrap:42100"
      FID_RPC_ADV_ADDR: "bootstrap:8800"

  peer1:
    image: fid
    command: ["-retry-join=bootstrap:32100", "-debug"]
    ports:
      - "8801:8800"
      - "9091:9090"
      - "42101:42100/udp"
      - "42101:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer1:32100"
      FID_DATA_ADV_ADDR: "peer1:42100"
      FID_RPC_ADV_ADDR: "peer1:8801"

  peer2:
    image: fid
    command: ["-retry-join=bootstrap:32100", "-debug"]
    ports:
      - "8802:8800"
      - "9092:9090"
      - "42102:42100/udp"
      - "42102:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer2:32100"
      FID_DATA_ADV_ADDR: "peer2:42100"
      FID_RPC_ADV_ADDR: "peer2:8802"

  peer3:
    image: fid
    command: ["-retry-join=peer1:32100", "-debug"]
    ports:
      - "8803:8800"
      - "9093:9090"
      - "42103:42100/udp"
      - "42103:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer3:32100"
      FID_DATA_ADV_ADDR: "peer3:42100"
      FID_RPC_ADV_ADDR: "peer3:8803"

  peer4:
    image: fid
    command: ["-retry-join=peer2:32100", "-debug"]
    ports:
      - "8804:8800"
      - "9094:9090"
      - "42104:42100/udp"
      - "42104:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer4:32100"
      FID_DATA_ADV_ADDR: "peer4:42100"
      FID_RPC_ADV_ADDR: "peer4:8804"

  peer5:
    image: fid
    command: ["-retry-join=peer1:32100", "-debug"]
    ports:
      - "8805:8800"
      - "9095:9090"
      - "42105:42100/udp"
      - "42105:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer5:32100"
      FID_DATA_ADV_ADDR: "peer5:42100"
      FID_RPC_ADV_ADDR: "peer5:8805"

  peer6:
    image: fid
    command: ["-retry-join=bootstrap:32100", "-debug"]
    ports:
      - "8806:8800"
      - "9096:9090"
      - "42106:42100/udp"
      - "42106:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer6:32100"
      FID_DATA_ADV_ADDR: "peer6:42100"
      FID_RPC_ADV_ADDR: "peer6:8806"

  peer7:
    image: fid
    command: ["-retry-join=bootstrap:32100", "-debug"]
    ports:
      - "8807:8800"
      - "9097:9090"
      - "42107:42100/udp"
      - "42107:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer7:32100"
      FID_DATA_ADV_ADDR: "peer7:42100"
      FID_RPC_ADV_ADDR: "peer7:8807"

  peer8:
    image: fid
    command: ["-retry-join=bootstrap:32100", "-debug"]
    ports:
      - "8808:8800"
      - "9098:9090"
      - "42108:42100/udp"
      - "42108:42100/tcp"
    environment:
      FID_GOSSIP_ADV_ADDR: "peer8:32100"
      FID_DATA_ADV_ADDR: "peer8:42100"
      FID_RPC_ADV_ADDR: "peer8:8808"
