#!/bin/bash
#
# This script is a fidias key value client using the fidias http gateway.
#

source $(dirname $0)/common.sh

USAGE=`cat <<EOF

  Usage: $0 <cmd> [options]

    stat        <remote-path>
    versions    <remote-path>
    mkdir       <remote-path>
    push        <remote-path> <local-path>
    pull        <remote-path>
  
EOF`


usage_exit() {
	echo "${USAGE}";
	exit $1;
}

if [ "${#@}" -lt 2 ]; then
  usage_exit 2;
fi

cmd=$1
key=$2
value=$3

case $cmd in
  stat)
    curl -v "${host}/${p_fs}/${key}?stat" | jq .
    ;;
  versions)
    curl -v "${host}/${p_fs}/${key}?versions" | jq .
    ;;
  mkdir)
	curl -v -XPOST ${host}/${p_fs}/${key}/
    ;;
  pull)
    curl -v -O ${host}/${p_fs}/${key}
    ;;
  push)
	if [ "${value}" == "" ]; then
		usage_exit 3;
	fi
    curl -v -L ${host}/${p_fs}/${key} --data-binary @"${value}" | jq .
    ;;
  *)
	usage_exit 4;
	;;
esac
