#!/bin/bash

source $(dirname $0)/common.sh

USAGE="\n  Usage: $0 <key>\n"

if [ "${#@}" -ne 1 ]; then
  echo -e "${USAGE}"
  exit 2;
fi

data=`http_get "${host}/${p_locate}/${key}"`
echo ;
indent "$data" "  "
echo ;

